# Generated by Django 5.2.8 on 2025-11-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocks',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cocks',
            name='category',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cocks',
            name='heart',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cocks',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cocks',
            name='spar_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cocks',
            name='victory',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cocks',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
