# Generated by Django 5.2.8 on 2025-11-28 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comments_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='cock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.cocks'),
            preserve_default=False,
        ),
    ]
